import { Product } from "./types/Product";

export const sampleProducts: Product[] = [
  {
    name: "Nike Slim shirt",
    slug: "nike-slim-shirt",
    image: "../images/p1.jpg",
    category: "Shirts",
    brand: "Nike",
    price: 120,
    countInStock: 10,
    description: "High Quality Shirt",
    rating: 4.5,
    numReviews: 11,
  },
  {
    name: "Addidas fit shirt",
    slug: "Addidas-fit-shirt",
    image: "../images/p2.jpg",
    category: "Shirts",
    brand: "Addidas",
    price: 100,
    countInStock: 9,
    description: "High Quality Products",
    rating: 4,
    numReviews: 8,
  },
  {
    name: "Lacoste free pants",
    slug: "lacoste-free-pants",
    image: "../images/p3.jpg",
    category: "Pants",
    brand: "Lacoste",
    price: 220,
    countInStock: 0,
    description: "High Quality Products",
    rating: 4,
    numReviews: 12,
  },
  {
    name: "Nike Slim paint",
    slug: "nike-slim-paint",
    image: "../images/p4.jpg",
    category: "Paints",
    brand: "Nike",
    price: 300,
    countInStock: 13,
    description: "High Quality Shirt",
    rating: 3,
    numReviews: 7,
  },
];
